# Generated by Django 5.1.3 on 2024-11-23 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TimeField()),
                ('reminder', models.BooleanField(default=False)),
                ('people', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('importance', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('status', models.CharField(choices=[('WILL', 'Will'), ('DOING', 'Doing'), ('DONE', 'Done')], default='WILL', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('sub_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WILL', 'Will'), ('DONE', 'Done')], default='WILL', max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task')),
            ],
        ),
    ]
